//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialLog
    {
        public int idHistorialLog { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
