//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumentalAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBRemoteConnection : DbContext
    {
        public DBRemoteConnection()
            : base("name=DBRemoteConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Carpeta> Carpetas { get; set; }
        public virtual DbSet<Documento> Documentos { get; set; }
        public virtual DbSet<FlujoDocumento> FlujoDocumentoes { get; set; }
        public virtual DbSet<HistorialLog> HistorialLogs { get; set; }
        public virtual DbSet<Historico> Historicoes { get; set; }
        public virtual DbSet<PermisoDenegado> PermisoDenegadoes { get; set; }
        public virtual DbSet<Permiso> Permisos { get; set; }
        public virtual DbSet<Procedimiento> Procedimientos { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumentoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
