//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDocumentalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisoDenegado
    {
        public int idPermisoD { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> idPermiso { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Permiso Permiso { get; set; }
    }
}
